# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb25a98def8ad161bee790892626222282d211f8bc992c99b846fadf5e3b13140c261bd60881e4e454e41f8db963ce270e0c3fbc6fbed3dcc715369bfb1ed01

test:
  secret_key_base: 29977a1e92c9dc703e0a2406d23b3cc02d1733884095846434688fd8a2c11f383391aecd0c2f8570e413cad4e13c8fb1d20fbe0f83ef2487306fa540a975bf72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
